### PR TITLE
add subnet ids variables

### PR DESCRIPTION
**Pull request by davidbennatan**
add subnet ids variables

### CODE REVIEW

**Comment by davidbennatan** [comment]
I have a vpc with both private and public networks, so i need the option to chose the elastic group subnet location.
I test on my private enviroment on my fork, with both inserted and default  arguments

**Comment by brikis98** [comment]
OK, important sanity check: [as mentioned here](https://github.com/hashicorp/terraform-aws-consul#how-to-use-this-module), [here](https://github.com/hashicorp/terraform-aws-consul/tree/master/examples/root-example), and [here](https://github.com/hashicorp/terraform-aws-consul/blob/master/main.tf#L3) the code in the root of this module is *example code*. It is meant to show one simple way to use the modules in the `modules` folder and not to be used directly in prod. I appreciate the PR, and the changes you propose are reasonable, but they sound like you are trying to use the code in the root directly for a real use-case...

**Comment by davidbennatan** [comment]
You right, my environment is not yet prod, but i should switch to use the inner modules directly.
nonetheless  I think that the changes will slightly increase the example code flexibility

**Comment by brikis98** [comment]
> I think that the changes will slightly increase the example code flexibility

True, but at the cost of making the examples harder to read, maintain, and test. If you think this is a critical change to have, I can merge it in, but otherwise, I'm not sure it's worth the extra overhead.

**Comment by davidbennatan** [comment]
Well, I cant really call this change critical, I should just switch and use the inner modules directly as I supposed to.
thanks for the review.

**Pull request closed without merging**
