### PR TITLE
Update systemd-resolved script for Ubuntu 20.04

### PR DESCRIPTION
**Pull request by mpluhar**
Creating this PR and closing https://github.com/hashicorp/terraform-aws-consul/pull/197 due to github account changes.

### CODE REVIEW

**Review by brikis98 — APPROVED** [review]
This looks great, thank you! I'll kick off tests now.

**Comment by brikis98** [comment]
Ah, pre-commit hook failed:

```
Terraform fmt............................................................Passed
gofmt....................................................................Failed
- hook id: gofmt
- files were modified by this hook

test/consul_cluster_test.go
```

Please run `go fmt`!

**Comment by mpluhar** [comment]
The neverending PR!  I have just updated it.

**Comment by brikis98** [comment]
Thanks, kicking off tests again.

**Comment by brikis98** [comment]
Tests passed! Merging now.

**Comment by brikis98** [comment]
https://github.com/hashicorp/terraform-aws-consul/releases/tag/v0.9.1

**Pull request merged**
