### PR TITLE
bump consul version to 1.0.0

### PR DESCRIPTION
**Pull request by mbravorus**
update consul version in example code to 1.0.0

### CODE REVIEW

**Comment by brikis98** [comment]
Thanks for the PR!

How did you test this change?

**Comment by mbravorus** [comment]
Tested by building the images form the example, successfully:

==> ubuntu16-ami: Creating the AMI: consul-ubuntu-2017-11-14T11-52-04Z
==> amazon-linux-ami: Creating the AMI: consul-amazon-linux-2017-11-14T11-52-04Z

**Comment by brikis98** [comment]
Did you try running the new images in the root example in this repo to see if they still work correctly?

**Comment by mbravorus** [comment]
Yep. Fresh proof from the helper script:

2017-11-14 15:16:59 [INFO] [consul-examples-helper.sh] All 3 Consul servers have registered in the cluster!

**Comment by brikis98** [comment]
Wonderful, thank you!

**Comment by brikis98** [comment]
https://github.com/hashicorp/terraform-aws-consul/releases/tag/v0.1.0

**Pull request merged**
